-- =============================================================================
-- 0007 -- authentication: credentials, sessions, and the identity policies
-- 0004 left for later.
--
-- 0003 deliberately punted this ("credentials get their own table when that
-- decision is made") because how a user proves who they are differs by
-- deployment and guessing would have baked a choice into the ledger schema
-- while it was still empty. The decision is now made: password + session,
-- one path for both the desktop app and hosted/on-prem installs.
--
-- Two new tables, both identity-shaped rather than tenant-shaped -- no
-- workspace_id, same as `users` (0003's "second documented exception").
-- A session is not scoped to one workspace: the client sends
-- X-Workspace-Id per request, and which workspaces a session's user may
-- reach is answered by `workspace_members`, not by the session itself.
--
-- ROLE-NAME ORDERING: db/README.md is explicit that `npm run db:apply` runs
-- migrations *before* db/roles.sql, so the `accounting_auth` role this file
-- writes policies for does not exist yet when this migration applies to a
-- fresh database. `CREATE POLICY ... TO accounting_auth` would fail outright
-- in that case -- Postgres validates a `TO` role against pg_authid at
-- creation time, unlike a plain string literal. So every policy below reads
-- `current_user = 'accounting_auth'` instead: a runtime comparison with no
-- dependency on the role already existing. db/roles.sql creates the role and
-- grants it just enough privilege for these policies to ever admit anything.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- Credentials
-- -----------------------------------------------------------------------------

-- Split from `users` on purpose: only accounting_auth ever needs to read a
-- password hash, and giving accounting_app -- the role every ordinary
-- request runs as -- a reason to even have a column for one is the mistake
-- this avoids. See the REVOKE in db/roles.sql that closes the gap
-- ALTER DEFAULT PRIVILEGES would otherwise open for this table.
CREATE TABLE user_credentials (
    user_id       uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    password_hash text NOT NULL,
    version       integer NOT NULL DEFAULT 1,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

-- guard_mutable_row() (0001) is not reused here: it unconditionally reads
-- new.workspace_id/old.workspace_id to guard the tenant boundary, and
-- user_credentials has no such column -- identity is global (0003/0004's
-- "Identity" section), same as `users` and `workspaces` before it.
-- guard_workspace_version() (0006) was already carved out of
-- guard_mutable_row() for exactly this reason, but reusing a function named
-- for workspaces here would misdescribe what it's guarding, so this gets
-- its own copy of the same shape instead.
CREATE OR REPLACE FUNCTION guard_identity_row_version() RETURNS trigger AS $fn$
BEGIN
    new.version    := old.version + 1;
    new.updated_at := now();
    RETURN new;
END;
$fn$ LANGUAGE plpgsql;

CREATE TRIGGER trg_user_credentials_version
    BEFORE UPDATE ON user_credentials
    FOR EACH ROW EXECUTE FUNCTION guard_identity_row_version();


-- -----------------------------------------------------------------------------
-- Sessions
-- -----------------------------------------------------------------------------

-- `token_hash`, never the raw token -- the same reasoning as a password
-- hash: a database read (backup, replica, compromised connection) must not
-- be enough on its own to hand out a live, usable session. The raw token is
-- generated by the API, returned to the client once in a Set-Cookie header,
-- and never stored anywhere.
CREATE TABLE sessions (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash   text NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz NOT NULL,
    -- NULL = active. Logout sets this rather than deleting the row, so a
    -- replayed stolen cookie has something to be checked against instead of
    -- simply finding no row and failing open by accident.
    revoked_at   timestamptz
);

CREATE UNIQUE INDEX uq_sessions_token_hash ON sessions (token_hash);
CREATE INDEX idx_sessions_user ON sessions (user_id);

-- No version/guard_mutable_row trigger: sessions are never PATCHed by a
-- client against an optimistic-concurrency version the way a ledger row is.
-- They are created, resolved, and revoked -- three narrow operations, not a
-- general mutable resource.


-- -----------------------------------------------------------------------------
-- Row-level security
-- -----------------------------------------------------------------------------

ALTER TABLE user_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions          ENABLE ROW LEVEL SECURITY;

CREATE POLICY user_credentials_auth_only ON user_credentials FOR ALL
    USING (current_user = 'accounting_auth')
    WITH CHECK (current_user = 'accounting_auth');

CREATE POLICY sessions_auth_only ON sessions FOR ALL
    USING (current_user = 'accounting_auth')
    WITH CHECK (current_user = 'accounting_auth');

-- `users` (0004) carries a SELECT-only policy scoped to co-members, and
-- deliberately no INSERT/UPDATE/DELETE policy at all -- its comment says
-- this is the seam for when identity is decided. It is decided now:
-- accounting_auth gets full access, nothing else changes for accounting_app.
CREATE POLICY users_auth_full_access ON users FOR ALL
    USING (current_user = 'accounting_auth')
    WITH CHECK (current_user = 'accounting_auth');

-- `workspace_members` (0004) is an ordinary tenant table: invisible without
-- app.workspace_id set. Auth connections never set it -- identity is global
-- -- so without this, accounting_auth could not answer "which workspaces,
-- and what role in each" for a session's user across every tenant at once,
-- which is exactly what login and GET /auth/me need. Membership rows
-- themselves are still written through accounting_app, workspace-scoped,
-- same as before -- this is read-only.
CREATE POLICY workspace_members_auth_read ON workspace_members FOR SELECT
    USING (current_user = 'accounting_auth');
